CREATE DATABASE db_sp
ON

( NAME = db_sp_DAT,
	FILENAME = 'D:\SQL2019\BANCOS_DE_DADOS\BD_PROCEDURES\db_sp_Dados.mdf',
	SIZE = 10,
	MAXSIZE = 50,
	FILEGROWTH = 5 )

LOG ON
( NAME = db_sp_LOG,
	FILENAME = 'D:\SQL2019\BANCOS_DE_DADOS\BD_PROCEDURES\db_sp_log.ldf',
	SIZE = 5MB,
	MAXSIZE = 25MB,
	FILEGROWTH = 5MB)

GO