CREATE DATABASE empresa

ON (
	NAME = empresa_DATA,
	FILENAME = 'D:\SQL2019\BANCOS_DE_DADOS\BD_EMPRESA\empresa_Dados.mdf',
	SIZE = 25,
	MAXSIZE = 100,
	FILEGROWTH = 5 )

 LOG ON (
	NAME = empresa_LOG,
	FILENAME = 'D:\SQL2019\BANCOS_DE_DADOS\BD_EMPRESA\empresa_Log.ldf',
	SIZE = 10MB,
	MAXSIZE = 50MB,
	FILEGROWTH = 5MB )
GO