USE BD_JOINS

SELECT * FROM DEPARTAMENTO
SELECT * FROM FUNCIONARIO
SELECT * FROM FUNCAO

SELECT * FROM
	FUNCIONARIO AS FC
INNER JOIN 
	DEPARTAMENTO AS DP
ON FC.CODDEPTO = DP.CODIGO


SELECT F.MATRICULA, F.NOME, F.SALARIO, F.CODDEPTO, D.CODIGO, D.DESCRICAO AS 'DEPARTAMENTO'
	FROM FUNCIONARIO AS F
INNER JOIN
	DEPARTAMENTO AS D
ON F.CODDEPTO = D.CODIGO

-- --------------------------------------------------------------------------------------------

SELECT F.MATRICULA, F.NOME, F.SALARIO, F.CODDEPTO, D.CODIGO, D.DESCRICAO AS 'DEPARTAMENTO'
	FROM FUNCIONARIO AS F
LEFT JOIN
	DEPARTAMENTO AS D
ON F.CODDEPTO = D.CODIGO

-- --------------------------------------------------------------------------------------------

SELECT F.MATRICULA, F.NOME, F.SALARIO, F.CODDEPTO, D.CODIGO, D.DESCRICAO AS 'DEPARTAMENTO'
	FROM FUNCIONARIO AS F
RIGHT JOIN
	DEPARTAMENTO AS D
ON F.CODDEPTO = D.CODIGO

-- ---------------------------------------------------------------------------------------------

SELECT F.MATRICULA, F.NOME, F.SALARIO, F.CODDEPTO, D.CODIGO, D.DESCRICAO AS 'DEPARTAMENTO'
	FROM FUNCIONARIO AS F
FULL JOIN
	DEPARTAMENTO AS D
ON F.CODDEPTO = D.CODIGO

WHERE F.CODDEPTO IS NULL
AND	D.CODIGO IS NULL

-- ---------------------------------------------------------------------------------------------